// <auto-generated />
using LoginAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginAPI.Migrations
{
    [DbContext(typeof(DataBaseContecst))]
    [Migration("20240903121954_Sunrise")]
    partial class Sunrise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoginAPI.Models.Contacts", b =>
                {
                    b.Property<int>("Contact_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contact_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Contact_ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("LoginAPI.Models.Message", b =>
                {
                    b.Property<int>("Message_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Message_Id"));

                    b.Property<string>("Client_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message_Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Theme_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Message_Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("LoginAPI.Models.MessageThemes", b =>
                {
                    b.Property<int>("MT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MT_ID"));

                    b.Property<string>("MessageTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MT_ID");

                    b.ToTable("MessageThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
